# Definiere das Docker-Image für den GitLab Runner

stages:
  - build
  - test
  - deploy
cache:
  paths:
    - frontend/node_modules/
    - backend/.venv/ 

react_build:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - echo Installiere npm-packages
    - npm install 
    - echo Baue das Frontend
    - CI=false npm run build


backend_build:
  stage: build
  image: python:3.9
  cache:
    key: python-cache
    paths:
      - .cache/pip
      - backend/.venv/
  script:
    - cd backend
    - echo "Building the Backend"
    - pip install --cache-dir .cache/pip -r requirements.txt
    # - echo "Starting the Python application"
    # - python main.py &
    # - APP_PID=$!
    # - sleep 10 # Allow some time for the application to start
    # - ps -p $APP_PID > /dev/null && echo "Application is running" || (echo "Application failed to start" && exit 1)
    # - kill $APP_PID # Clean up: stop the application


react_test:
 stage: test
 script:
   - cd frontend
   - echo Installiere npm-packages
   - npm install
   - echo Teste das Frontend
   - CI=false npm run test

deploy_Production:
  image: ubuntu:latest
  stage: deploy
  
  before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh mindmachine@141.45.224.114 "cd ./mindmachine/ && git reset --hard HEAD && git clean -f -d && git pull  && docker-compose down && docker-compose up --build -d && exit"
  only:
    - main



