import React, { useEffect, useState } from "react";
import "../../styles/SearchResult/SearchResult.css";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import Button from "@mui/material/Button";
import SearchInput from "../Home/SearchInput";
import { Alert, AlertTitle } from "@mui/material";
import DemoPaper from "@mui/material/Paper";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFilePdf } from "@fortawesome/free-solid-svg-icons";

const SearchResult = () => {
  const [fileBlob, setFileBlob] = useState("");

  useEffect(() => {

    const API_GetDocument = async () => {
      const user_id = localStorage.getItem("userID");
      const fileName = localStorage.getItem("fileName");

      const fetchString = `http://localhost:8000/document?user_id=${user_id}&document_name=${fileName}`;
      return await fetch(fetchString, {
        method: "GET",
      }).then(async (res) => {
        console.log(res);

        const blob = await res.blob();
        const pdfUrl = URL.createObjectURL(blob);
        console.log(blob);
        console.log(pdfUrl);
        setFileBlob(pdfUrl);
        //console.log(filename);
        //setPDFURL(pdfUrl);
      });
    };
    API_GetDocument()
  }, []);
  return (
    <div style={{ marginTop: 20 }}>
      <SearchInput></SearchInput>

      <Alert id="Alert" severity="success">
        <AlertTitle>The Answer has been generated by AI</AlertTitle>
        This is a success alert — <strong>check it out!</strong>
      </Alert>

      <div
        style={{ display: "flex", flexWrap: "nowrap", flexDirection: "row" }}
      >
        <Card
          elevation={3}
          id="SearchResultCard"
          style={{
            display: "flex",
            marginRight: 50,
            minWidth: "60%",
            flexDirection: "column",
          }}
        >
          <CardContent style={{ minHeight: 200 }}>
              <iframe
              title="pdf-viewer"
              width={"100%"}
              height={"700"}
              src={fileBlob}
            ></iframe>
          </CardContent>
          <CardActions
            style={{
              justifyContent: "space-between",
              backgroundColor: "GrayText",
              minHeight: 60,
            }}
          >
            <Button id="OpenPDF">Open PDF</Button>
            <Button id="CopyResult">Copy Result</Button>
          </CardActions>
        </Card>

        <DemoPaper id="DemoPaper">
          <FontAwesomeIcon id="FontAwesomeIcon" size="5x" icon={faFilePdf} />
          <h4>Name der Datei </h4>
        </DemoPaper>
      </div>
    </div>
  );
};
export default SearchResult;
